version: '3'

services:
  document-processor:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./frontend:/app/static
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload